import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    })
);

// Cache the underlying font files with a cache-first strategy for 1 year
registerRoute(
    ({ url }) => url.origin === 'https://fonts.gstatic.com',
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
                maxEntries: 30,
            }),
        ],
    })
);

// Cache images with CacheFirst strategy
// Configurado para 300 imágenes (100 productos x 3 imágenes promedio) durante 30 días
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'product-images',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 300, // 100 productos x 3 imágenes promedio
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 días
            }),
        ],
    })
);

// Cache GraphQL API calls (GET y POST) para funcionamiento offline
// NetworkFirst con fallback a cache permite 30 días offline
registerRoute(
    ({ url, request }) => {
        // Captura tanto GET como POST requests a la API GraphQL
        return url.origin === 'https://api.escuelajs.co' && 
            (request.method === 'GET' || request.method === 'POST');
    },
    new NetworkFirst({
        cacheName: 'graphql-api-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 100, // Suficiente para múltiples queries
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 días - funciona offline
            }),
        ],
        networkTimeoutSeconds: 3, // Fallback a cache si red tarda >3s
    })
);

// Cache CSS and JS with StaleWhileRevalidate
registerRoute(
    ({ request }) =>
        request.destination === 'style' || request.destination === 'script',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

// Default: Use NetworkFirst for navigation requests
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
        cacheName: 'pages',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
        networkTimeoutSeconds: 3, // Fallback a cache si red tarda >3s
    })
);

// Listen for messages from the app
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Notify clients when a new service worker is activated
self.addEventListener('activate', (event) => {
    event.waitUntil(
        clients.matchAll({ type: 'window' }).then((clients) => {
            clients.forEach((client) => {
                client.postMessage({
                    type: 'SW_ACTIVATED',
                    message: 'Service Worker activated successfully',
                });
            });
        })
    );
});
